version: "2"
run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: true
  modules-download-mode: mod
  allow-parallel-runners: true
linters:
  exclusions:
    rules:
        - path: _test\.go
          linters:
            - gocyclo
            - errcheck
            - dupl
            - gosec