// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/customer_account.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/customer_account.go -destination test/mock/repository/customer_account.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	uuid "github.com/gofrs/uuid/v5"
	models "github.com/tiagovaldrich/accounts-api/internal/models"
	repository "github.com/tiagovaldrich/accounts-api/internal/repository"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomerAccountRepository is a mock of CustomerAccountRepository interface.
type MockCustomerAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerAccountRepositoryMockRecorder is the mock recorder for MockCustomerAccountRepository.
type MockCustomerAccountRepositoryMockRecorder struct {
	mock *MockCustomerAccountRepository
}

// NewMockCustomerAccountRepository creates a new mock instance.
func NewMockCustomerAccountRepository(ctrl *gomock.Controller) *MockCustomerAccountRepository {
	mock := &MockCustomerAccountRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerAccountRepository) EXPECT() *MockCustomerAccountRepositoryMockRecorder {
	return m.recorder
}

// CreateCustomerAccount mocks base method.
func (m *MockCustomerAccountRepository) CreateCustomerAccount(ctx context.Context, customerAccount models.CustomerAccount) (*models.CustomerAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomerAccount", ctx, customerAccount)
	ret0, _ := ret[0].(*models.CustomerAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomerAccount indicates an expected call of CreateCustomerAccount.
func (mr *MockCustomerAccountRepositoryMockRecorder) CreateCustomerAccount(ctx, customerAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomerAccount", reflect.TypeOf((*MockCustomerAccountRepository)(nil).CreateCustomerAccount), ctx, customerAccount)
}

// GetDB mocks base method.
func (m *MockCustomerAccountRepository) GetDB(ctx context.Context) bun.IDB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB", ctx)
	ret0, _ := ret[0].(bun.IDB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockCustomerAccountRepositoryMockRecorder) GetDB(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockCustomerAccountRepository)(nil).GetDB), ctx)
}

// SearchCustomerAccountByID mocks base method.
func (m *MockCustomerAccountRepository) SearchCustomerAccountByID(ctx context.Context, customerAccountID *uuid.UUID) (*repository.CustomerAccountByIDResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCustomerAccountByID", ctx, customerAccountID)
	ret0, _ := ret[0].(*repository.CustomerAccountByIDResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCustomerAccountByID indicates an expected call of SearchCustomerAccountByID.
func (mr *MockCustomerAccountRepositoryMockRecorder) SearchCustomerAccountByID(ctx, customerAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCustomerAccountByID", reflect.TypeOf((*MockCustomerAccountRepository)(nil).SearchCustomerAccountByID), ctx, customerAccountID)
}

// SetDB mocks base method.
func (m *MockCustomerAccountRepository) SetDB(db bun.IDB) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDB", db)
}

// SetDB indicates an expected call of SetDB.
func (mr *MockCustomerAccountRepositoryMockRecorder) SetDB(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDB", reflect.TypeOf((*MockCustomerAccountRepository)(nil).SetDB), db)
}

// WithTransaction mocks base method.
func (m *MockCustomerAccountRepository) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockCustomerAccountRepositoryMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockCustomerAccountRepository)(nil).WithTransaction), ctx, fn)
}
